In [1]:
import pandas as pd

In [2]:
#reading in data
df = pd.read_csv('all_crime_cleaned3.csv')

In [3]:
#looking at data
df.shape

(73554, 58)

In [4]:
#looking at data
df.head()

,Unnamed: 0,Areaname,CRM110181D,CRM110182D,CRM110183D,CRM110184D,CRM110185D,CRM110186D,CRM110187D,CRM110188D,...,CRM210200D,CRM210208D,CRM210198D,CRM210206D,CRM210187D,CRM210191D,CRM210181D,CRM210197D,CRM210183D,CRM210195D
0,0,UNITED STATES,1290984.0,1258669.0,1213412.0,1186852.0,1305302.0,1456793.0,1439560.0,1376000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ALABAMA,17871.0,17265.0,16240.0,16858.0,18105.0,22009.0,21996.0,21680.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Autauga, AL",127.0,142.0,129.0,91.0,94.0,197.0,140.0,206.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Baldwin, AL",243.0,309.0,299.0,423.0,288.0,135.0,224.0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"Barbour, AL",91.0,90.0,85.0,94.0,93.0,74.0,109.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Renaming columns I want
df.rename(columns={u'CRM110181D':'VC1981',
                     u'CRM110182D':'VC1982',
                     u'CRM110183D':'VC1983', 
                     u'CRM110184D':'VC1984', 
                     u'CRM110185D':'VC1985', 
                     u'CRM110186D':'VC1986', 
                     u'CRM110187D':'VC1987', 
                     u'CRM110188D':'VC1988', 
                     u'CRM110189D':'VC1989',
                     u'CRM110190D':'VC1990', 
                     u'CRM110191D':'VC1991', 
                     u'CRM110192D':'VC1992', 
                     u'CRM110193D':'VC1993', 
                     u'CRM110194D':'VC1994', 
                     u'CRM110195D':'VC1995', 
                     u'CRM110196D':'VC1996', 
                     u'CRM110197D':'VC1997', 
                     u'CRM110198D':'VC1998', 
                     u'CRM110199D':'VC1999', 
                     u'CRM110200D':'VC2000', 
                     u'CRM110201D':'VC2001', 
                     u'CRM110202D':'VC2002', 
                     u'CRM110203D':'VC2003', 
                     u'CRM110204D':'VC2004', 
                     u'CRM110205D':'VC2005', 
                     u'CRM110206D':'VC2006', 
                     u'CRM110207D':'VC2007', 
                     u'CRM110208D':'VC2008'}, inplace=True)
df.rename(columns={u'CRM210181D':'NVC1981',
u'CRM210182D':'NVC1982',
 u'CRM210183D':'NVC1983',
 u'CRM210184D':'NVC1984',
 u'CRM210185D':'NVC1985',
 u'CRM210186D':'NVC1986',
 u'CRM210187D':'NVC1987',
 u'CRM210188D':'NVC1988',
 u'CRM210189D':'NVC1989',
 u'CRM210190D':'NVC1990',
 u'CRM210191D':'NVC1991',
 u'CRM210192D':'NVC1992',
 u'CRM210193D':'NVC1993',
 u'CRM210194D':'NVC1994',
 u'CRM210195D':'NVC1995',
 u'CRM210196D':'NVC1996',
 u'CRM210197D':'NVC1997',
 u'CRM210198D':'NVC1998',
 u'CRM210199D':'NVC1999',
 u'CRM210200D':'NVC2000',
 u'CRM210201D':'NVC2001',
 u'CRM210202D':'NVC2002',
 u'CRM210203D':'NVC2003',
 u'CRM210204D':'NVC2004',
 u'CRM210205D':'NVC2005',
 u'CRM210206D':'NVC2006',
 u'CRM210207D':'NVC2007',
 u'CRM210208D':'NVC2008'}, inplace=True)

In [6]:
print (type(df))
print (df.shape)

<class 'pandas.core.frame.DataFrame'>
(73554, 58)

In [7]:
df.head()

,Unnamed: 0,Areaname,VC1981,VC1982,VC1983,VC1984,VC1985,VC1986,VC1987,VC1988,...,NVC2000,NVC2008,NVC1998,NVC2006,NVC1987,NVC1991,NVC1981,NVC1997,NVC1983,NVC1995
0,0,UNITED STATES,1290984.0,1258669.0,1213412.0,1186852.0,1305302.0,1456793.0,1439560.0,1376000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ALABAMA,17871.0,17265.0,16240.0,16858.0,18105.0,22009.0,21996.0,21680.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Autauga, AL",127.0,142.0,129.0,91.0,94.0,197.0,140.0,206.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Baldwin, AL",243.0,309.0,299.0,423.0,288.0,135.0,224.0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"Barbour, AL",91.0,90.0,85.0,94.0,93.0,74.0,109.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# splitting the AReaname column into state and county columns
# then renaming columns appopriatly
loc = df['Areaname'].str.split(',', expand=True)
df = pd.concat([loc, df])

In [9]:
df.rename(columns={0:'County',
                  1:'State'}, inplace=True)
df.head()

,County,State,Areaname,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
0,UNITED STATES,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Autauga,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Baldwin,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Barbour,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Sorting to only get counties from NY
df1 = df[df.State == ' NY']

In [11]:
# Sorting to get NYC
dfQ = df1[(df1.County =='Queens' )]
dfbk = df1[(df1.County =='Kings' )]
dfbx = df1[(df1.County =='Bronx' )]
dfm = df1[(df1.County =='New York' )]
dfsi = df1[(df1.County =='Richmond' )]
df2 = pd.concat([dfQ, dfbk, dfbx, dfm, dfsi], axis=0)

In [12]:
dfsi.shape

(23, 60)

In [13]:
# so It looks like this dataset was poorly managed,
# the crimes per county was totaled an assigned to kings county(Brooklyn)
df2.head(2)

,County,State,Areaname,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
1903,Queens,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5101,Queens,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df2.shape

(115, 60)

In [15]:
nyc_df = df2[(df2.County == 'Kings')]
nyc_df.shape

(23, 60)

In [16]:
nyc_df = df2.drop(['County', 'State', 'Unnamed: 0', 'Areaname'], axis=1)
nyc_df.shape

(115, 56)

In [17]:
nyc_df.shape

(115, 56)

In [18]:
nyc_df

,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,NVC1988,NVC1989,NVC1990,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
1903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
nyc_df.isnull().sum()

NVC1981    115
NVC1982    115
NVC1983    115
NVC1984    115
NVC1985    115
NVC1986    115
NVC1987    115
NVC1988    115
NVC1989    115
NVC1990    115
NVC1991    115
NVC1992    115
NVC1993    115
NVC1994    115
NVC1995    115
NVC1996    115
NVC1997    115
NVC1998    115
NVC1999    115
NVC2000    115
NVC2001    115
NVC2002    115
NVC2003    115
NVC2004    115
NVC2005    115
NVC2006    115
NVC2007    115
NVC2008    115
VC1981     115
VC1982     115
VC1983     115
VC1984     115
VC1985     115
VC1986     115
VC1987     115
VC1988     115
VC1989     115
VC1990     115
VC1991     115
VC1992     115
VC1993     115
VC1994     115
VC1995     115
VC1996     115
VC1997     115
VC1998     115
VC1999     115
VC2000     115
VC2001     115
VC2002     115
VC2003     115
VC2004     115
VC2005     115
VC2006     115
VC2007     115
VC2008     115
dtype: int64

In [ ]:
n