In [2]:
import pandas as pd

In [3]:
#reading in data
df = pd.read_csv('all_crime_cleaned3.csv')

In [4]:
#looking at data
df.shape

(73554, 58)

In [21]:
df.notnull().sum()

County        73554
State         72335
Areaname      73554
NVC1981        3198
NVC1982        3198
NVC1983        3198
NVC1984        3198
NVC1985        3198
NVC1986        3198
NVC1987        3198
NVC1988        3198
NVC1989        3198
NVC1990        3198
NVC1991        3198
NVC1992        3198
NVC1993        3198
NVC1994        3198
NVC1995        3198
NVC1996        3198
NVC1997        3198
NVC1998        3198
NVC1999        3198
NVC2000        3198
NVC2001        3198
NVC2002        3198
NVC2003        3198
NVC2004        3198
NVC2005        3198
NVC2006        3198
NVC2007        3198
NVC2008        3198
Unnamed: 0    73554
VC1981         3198
VC1982         3198
VC1983         3198
VC1984         3198
VC1985         3198
VC1986         3198
VC1987         3198
VC1988         3198
VC1989         3198
VC1990         3198
VC1991         3198
VC1992         3198
VC1993         3198
VC1994         3198
VC1995         3198
VC1996         3198
VC1997         3198
VC1998         3198
VC1999         3198
VC2000         3198
VC2001         3198
VC2002         3198
VC2003         3198
VC2004         3198
VC2005         3198
VC2006         3198
VC2007         3198
VC2008         3198
dtype: int64

In [23]:
null = df[df.notnull()]
null
#drinks[drinks.continent.notnull()] # only show rows where continent is not missing

,County,State,Areaname,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
0,UNITED STATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Autauga,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Baldwin,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Barbour,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Bibb,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Blount,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Bullock,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Butler,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Calhoun,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Chambers,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Cherokee,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Chilton,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Choctaw,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Clarke,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Clay,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Cleburne,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Coffee,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Colbert,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Conecuh,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Coosa,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Covington,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Crenshaw,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Cullman,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Dale,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Dallas,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,DeKalb,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Elmore,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Escambia,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Etowah,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73524,NaN,NaN,"Washington, WI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73525,NaN,NaN,"Waukesha, WI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73526,NaN,NaN,"Waupaca, WI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73527,NaN,NaN,"Waushara, WI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73528,NaN,NaN,"Winnebago, WI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73529,NaN,NaN,"Wood, WI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73530,NaN,NaN,WYOMING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73531,NaN,NaN,"Albany, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73532,NaN,NaN,"Big Horn, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73533,NaN,NaN,"Campbell, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73534,NaN,NaN,"Carbon, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73535,NaN,NaN,"Converse, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73536,NaN,NaN,"Crook, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73537,NaN,NaN,"Fremont, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73538,NaN,NaN,"Goshen, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73539,NaN,NaN,"Hot Springs, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73540,NaN,NaN,"Johnson, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73541,NaN,NaN,"Laramie, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73542,NaN,NaN,"Lincoln, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73543,NaN,NaN,"Natrona, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73544,NaN,NaN,"Niobrara, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73545,NaN,NaN,"Park, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73546,NaN,NaN,"Platte, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73547,NaN,NaN,"Sheridan, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73548,NaN,NaN,"Sublette, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73549,NaN,NaN,"Sweetwater, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73550,NaN,NaN,"Teton, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73551,NaN,NaN,"Uinta, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73552,NaN,NaN,"Washakie, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73553,NaN,NaN,"Weston, WY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#looking at data
df.head()

,Unnamed: 0,Areaname,CRM110181D,CRM110182D,CRM110183D,CRM110184D,CRM110185D,CRM110186D,CRM110187D,CRM110188D,...,CRM210200D,CRM210208D,CRM210198D,CRM210206D,CRM210187D,CRM210191D,CRM210181D,CRM210197D,CRM210183D,CRM210195D
0,0,UNITED STATES,1290984.0,1258669.0,1213412.0,1186852.0,1305302.0,1456793.0,1439560.0,1376000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ALABAMA,17871.0,17265.0,16240.0,16858.0,18105.0,22009.0,21996.0,21680.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Autauga, AL",127.0,142.0,129.0,91.0,94.0,197.0,140.0,206.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Baldwin, AL",243.0,309.0,299.0,423.0,288.0,135.0,224.0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"Barbour, AL",91.0,90.0,85.0,94.0,93.0,74.0,109.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Renaming columns I want
df.rename(columns={u'CRM110181D':'VC1981',
                     u'CRM110182D':'VC1982',
                     u'CRM110183D':'VC1983', 
                     u'CRM110184D':'VC1984', 
                     u'CRM110185D':'VC1985', 
                     u'CRM110186D':'VC1986', 
                     u'CRM110187D':'VC1987', 
                     u'CRM110188D':'VC1988', 
                     u'CRM110189D':'VC1989',
                     u'CRM110190D':'VC1990', 
                     u'CRM110191D':'VC1991', 
                     u'CRM110192D':'VC1992', 
                     u'CRM110193D':'VC1993', 
                     u'CRM110194D':'VC1994', 
                     u'CRM110195D':'VC1995', 
                     u'CRM110196D':'VC1996', 
                     u'CRM110197D':'VC1997', 
                     u'CRM110198D':'VC1998', 
                     u'CRM110199D':'VC1999', 
                     u'CRM110200D':'VC2000', 
                     u'CRM110201D':'VC2001', 
                     u'CRM110202D':'VC2002', 
                     u'CRM110203D':'VC2003', 
                     u'CRM110204D':'VC2004', 
                     u'CRM110205D':'VC2005', 
                     u'CRM110206D':'VC2006', 
                     u'CRM110207D':'VC2007', 
                     u'CRM110208D':'VC2008'}, inplace=True)
df.rename(columns={u'CRM210181D':'NVC1981',
u'CRM210182D':'NVC1982',
 u'CRM210183D':'NVC1983',
 u'CRM210184D':'NVC1984',
 u'CRM210185D':'NVC1985',
 u'CRM210186D':'NVC1986',
 u'CRM210187D':'NVC1987',
 u'CRM210188D':'NVC1988',
 u'CRM210189D':'NVC1989',
 u'CRM210190D':'NVC1990',
 u'CRM210191D':'NVC1991',
 u'CRM210192D':'NVC1992',
 u'CRM210193D':'NVC1993',
 u'CRM210194D':'NVC1994',
 u'CRM210195D':'NVC1995',
 u'CRM210196D':'NVC1996',
 u'CRM210197D':'NVC1997',
 u'CRM210198D':'NVC1998',
 u'CRM210199D':'NVC1999',
 u'CRM210200D':'NVC2000',
 u'CRM210201D':'NVC2001',
 u'CRM210202D':'NVC2002',
 u'CRM210203D':'NVC2003',
 u'CRM210204D':'NVC2004',
 u'CRM210205D':'NVC2005',
 u'CRM210206D':'NVC2006',
 u'CRM210207D':'NVC2007',
 u'CRM210208D':'NVC2008'}, inplace=True)

In [7]:
print (type(df))
print (df.shape)

<class 'pandas.core.frame.DataFrame'>
(73554, 58)

In [8]:
df.head()

,Unnamed: 0,Areaname,VC1981,VC1982,VC1983,VC1984,VC1985,VC1986,VC1987,VC1988,...,NVC2000,NVC2008,NVC1998,NVC2006,NVC1987,NVC1991,NVC1981,NVC1997,NVC1983,NVC1995
0,0,UNITED STATES,1290984.0,1258669.0,1213412.0,1186852.0,1305302.0,1456793.0,1439560.0,1376000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ALABAMA,17871.0,17265.0,16240.0,16858.0,18105.0,22009.0,21996.0,21680.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Autauga, AL",127.0,142.0,129.0,91.0,94.0,197.0,140.0,206.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Baldwin, AL",243.0,309.0,299.0,423.0,288.0,135.0,224.0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"Barbour, AL",91.0,90.0,85.0,94.0,93.0,74.0,109.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.Areaname.dtypes()

TypeError: 'numpy.dtype' object is not callable

In [9]:
# splitting the AReaname column into state and county columns
# then renaming columns appopriatly
loc = df['Areaname'].str.split(',', expand=True)
df = pd.concat([loc, df])

In [10]:
df.rename(columns={0:'County',
                  1:'State'}, inplace=True)
df.head()

,County,State,Areaname,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
0,UNITED STATES,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Autauga,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Baldwin,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Barbour,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Sorting to only get counties from NY
df1 = df[df.State == ' NY']

In [12]:
# Sorting to get NYC
#dfQ = df1[(df1.County =='Queens' )]
dfbk = df1[(df1.County =='Kings' )]
#dfbx = df1[(df1.County =='Bronx' )]
#dfm = df1[(df1.County =='New York' )]
#dfsi = df1[(df1.County =='Richmond' )]
#df2 = pd.concat([dfQ, dfbk, dfbx, dfm, dfsi], axis=0)

In [13]:
dfsi.shape

(23, 60)

In [14]:
# so It looks like this dataset was poorly managed,
# the crimes per county was totaled an assigned to kings county(Brooklyn)
df2.head(2)

,County,State,Areaname,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
1903,Queens,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5101,Queens,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df2.shape

(115, 60)

In [16]:
nyc_df = df2[(df2.County == 'Kings')]
nyc_df.shape

(23, 60)

In [17]:
nyc_df

,County,State,Areaname,NVC1981,NVC1982,NVC1983,NVC1984,NVC1985,NVC1986,NVC1987,...,VC1999,VC2000,VC2001,VC2002,VC2003,VC2004,VC2005,VC2006,VC2007,VC2008
1886,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5084,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8282,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11480,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14678,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17876,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21074,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24272,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27470,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30668,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33866,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37064,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40262,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43460,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46658,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49856,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53054,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56252,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59450,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62648,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65846,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69044,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72242,Kings,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
dfbk.isnull().sum()

County         0
State          0
Areaname      23
NVC1981       23
NVC1982       23
NVC1983       23
NVC1984       23
NVC1985       23
NVC1986       23
NVC1987       23
NVC1988       23
NVC1989       23
NVC1990       23
NVC1991       23
NVC1992       23
NVC1993       23
NVC1994       23
NVC1995       23
NVC1996       23
NVC1997       23
NVC1998       23
NVC1999       23
NVC2000       23
NVC2001       23
NVC2002       23
NVC2003       23
NVC2004       23
NVC2005       23
NVC2006       23
NVC2007       23
NVC2008       23
Unnamed: 0    23
VC1981        23
VC1982        23
VC1983        23
VC1984        23
VC1985        23
VC1986        23
VC1987        23
VC1988        23
VC1989        23
VC1990        23
VC1991        23
VC1992        23
VC1993        23
VC1994        23
VC1995        23
VC1996        23
VC1997        23
VC1998        23
VC1999        23
VC2000        23
VC2001        23
VC2002        23
VC2003        23
VC2004        23
VC2005        23
VC2006        23
VC2007        23
VC2008        23
dtype: int64